# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Studio Meet Structure
email: will@covalent.design
description: > # this means to ignore newlines until "baseurl:"
  Website of Will Walker, with information on work at the MIT Design Lab, 3D Printing, hardware hacking, technical design projects, freshwater aquariums, parametric and programmatic design, objects that deform beautifully, and life in Cambridge, Massachusetts.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://studiomeetstructure.com" # the base hostname & protocol for your site
twitter_username: walkerwill
github_username:  colorofthesky

# Build settings
markdown: kramdown
